#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: v1
kind: Secret
metadata:
  name: wavefront
  namespace: petclinic
  labels:
    app: spring-petclinic
type: Opaque
data:
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI: #@ base64.encode(data.values.petclinic.wavefront.uri)
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN: #@ base64.encode(data.values.petclinic.wavefront.apiToken)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: petclinic
  labels:
    app: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: #@ data.values.petclinic.image
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 3
        env:
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
          valueFrom:
            secretKeyRef:
              name: wavefront
              key: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: wavefront
              key: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN
        - name: WAVEFRONT_APPLICATION_NAME
          value: #@ data.values.petclinic.wavefront.applicationName
        - name: WAVEFRONT_APPLICATION_SERVICE
          value: petclinic
        - name: spring_profiles_active
          value: mysql
        - name: MYSQL_URL
          value: "jdbc:mysql://petclinic-db-mysql/petclinic"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
  namespace: petclinic
  labels:
    app: spring-petclinic
spec:
  selector:
    app: spring-petclinic
  ports:
    - name: http
      protocol: TCP
      port: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spring-petclinic
  namespace: petclinic
  labels:
    app: spring-petclinic
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-contour-cluster-issuer
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: petclinic-tls
    hosts:
    - #@ data.values.petclinic.host
  rules:
  - host: #@ data.values.petclinic.host
    http:
      paths:
      - backend:
          serviceName: spring-petclinic
          servicePort: 8080
